### ISSUE TITLE
Не правильно считается secret_key

### ISSUE THREAD

**Issue by toporchillo** [Hector68/yandex-delivery#1]
Array ( [client_id] => Не удалось авторизоваться с указанным client_id [sender_id] => Указан некорректный sender_id [secret_key] => Заполните это поле [resourceKey] => Заполните это поле [hashValid] => Значение должно быть истинным. ) )

**Comment by Hector68** [comment]
Не указаны ключи. Они берутся в личном кабинете доставки.
Настраивает ApiConfig, где $method_keys и $data - текстовые поля, которые берутся в личном кабинете
$config = \Hector68\YandexDelivery\config\ApiProxyConfig($method_keys, $data);
